server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_HOST:registry-service}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/authentication/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**, /webjars/**, /v3/api-docs/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
          - Path=/api/v1/suscriptions/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**, /webjars/**, /v3/api-docs/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**, /webjars/**, /v3/api-docs/**
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/api/v1/deposit/**, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**, /webjars/**, /v3/api-docs/**
        - id: rooms-service
          uri: lb://rooms-service
          predicates:
            - Path=/api/v1/rooms/**, /api/v1/chat/**, /api/v1/player-lists/**, /ws/chat/**, /ws/chat, /swagger-ui.html, /swagger-ui/**, /swagger-resources/**, /webjars/**, /v3/api-docs/**